<h1><center> Tópicos Avançados em Python para Análise de Dados </center></h1>

![](https://drive.google.com/uc?export=view&id=1qCH-jlzKK1aFaTBpiTHN4qxTFrCVs720)

<center>
<h5>
O objetivo desse material é mostrar a você como aplicar diversos métodos das duas bibliotecas mais famosas para Ciência de Dados: Pandas e Seaborn. Ao longo do curso além de conhecermos como essas ferramentas funcionam vamos praticar a análise em dados reais e transformar os dados que temos em informações. 
Vamos nessa!
<h5>
<center>

## Módulo 5

### Exercício 1

#### Parte 1:

Os dados usados durante esse exercício foram obtidos a partir do relatório Women Entrepreneurship Index e Global Entrepreneurship Index publicado em 2015.A pesquisa é limitada aos países da OCDE, onde todos os dados de 2015 estão disponíveis ao mesmo tempo no banco de dados.Você consegue acessar mais informações através do [kaggle](https://www.kaggle.com/babyoda/women-entrepreneurship-and-labor-force).

A base de dados contém as seguintes informações: 

* **No** $\rightarrow$ ID do país em questão
* **Country** $\rightarrow$ nome do país
* **Level of development** $\rightarrow$ variável nominal para o índice de desenvolvimento
* **European Union Membership** $\rightarrow$ variável nominal para membros da União Europeia
* **Currency** $\rightarrow$ moeda presente no país
* **Women Entrepreneurship Index** $\rightarrow$ índice de empreendedorismo feminino 2015
* **Entrepreneurship Index** $\rightarrow$ índice de empreendedorismo 2015
* **Inflation rate** $\rightarrow$ taxa de inflação 2015
* **Female Labor Force Participation Rate** $\rightarrow$ taxa de participação feminina na força de trabalho de 2015

A partir dele, você deve obter informações sobre os dados guiado pelas perguntas e instruções abaixo

1) Importe as bibliotecas necessárias

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

2) Armazene os dados em uma variavel

In [ ]:
data = pd.read_csv('women.csv', sep=';')

3) Visualize as primeiras e as últimas 10 linhas dos dados

In [ ]:
data.head(10)

   No  Country  ... Inflation rate Female Labor Force Participation Rate
0   4  Austria  ...           0.90                                  67.1
1   6  Belgium  ...           0.60                                  58.0
2  17  Estonia  ...          -0.88                                  68.5
3  18  Finland  ...          -0.20                                  67.7
4  19   France  ...           0.00                                  60.6
5  20  Germany  ...           0.50                                  69.9
6  22   Greece  ...          -1.70                                  42.5
7  28  Ireland  ...          -0.30                                  59.4
8  30    Italy  ...           0.00                                  47.2
9  34   Latvia  ...           0.20                                  66.4

[10 rows x 9 columns]

In [ ]:
data.tail(10)

    No       Country  ... Inflation rate Female Labor Force Participation Rate
41  37      Malaysia  ...           2.30                                 58.50
42  38        Mexico  ...           2.70                                 44.70
43  42        Panama  ...           0.10                                 67.90
44  43          Peru  ...           3.50                                 63.40
45  47        Russia  ...          15.50                                 65.20
46  48  Saudi Arabia  ...           1.20                                 13.00
47  57      Thailand  ...          -0.90                                 62.00
48  58       Tunisia  ...           4.80                                 25.19
49  59        Turkey  ...           7.70                                 30.40
50  60       Uruguay  ...           8.67                                 68.00

[10 rows x 9 columns]

4) Identifique quais os tipos de dados temos em nosso conjunto e coloque as colunas de valores numéricos em uma variável

In [ ]:
data.dtypes

No                                         int64
Country                                   object
Level of development                      object
European Union Membership                 object
Currency                                  object
Women Entrepreneurship Index             float64
Entrepreneurship Index                   float64
Inflation rate                           float64
Female Labor Force Participation Rate    float64
dtype: object

In [ ]:
colunas_numericas = data.select_dtypes(include=['int64','float64'])
colunas_numericas.dtypes

No                                         int64
Women Entrepreneurship Index             float64
Entrepreneurship Index                   float64
Inflation rate                           float64
Female Labor Force Participation Rate    float64
dtype: object

5) Os países que apresentam as 10 maiores força de trabalho feminina são mais desenvolvidos ou em desenvolvimento?

In [ ]:
df = data.sort_values(by='Female Labor Force Participation Rate', ascending=False).head(10)

In [ ]:
df['Level of development'].value_counts()

Developed     8
Developing    2
Name: Level of development, dtype: int64

#### Parte 2

6) Na base de dados, qual a porcentagem de países presentes na União Europeia?

In [ ]:
valores = data['European Union Membership'].value_counts()

print('Não membros:', round(valores[0]/len(data),2))
print('Membros:', round(valores[1]/len(data), 2))

Não membros: 0.61
Membros: 0.39

7) Crie uma nova classificação de índice baixo, médio, alto e muito alto, para o empreendedoorismo feminino em cada um países. Para isso tome como intervalo os valores dos quartis dessa *feature*. Em qual classficação se encontra o Brasil? Quantos foram os países em cada uma das categorias?.

In [ ]:
bins = data['Women Entrepreneurship Index'].describe()
bins = bins[3:,].values

In [ ]:
data['classificacao'] = pd.cut(data['Women Entrepreneurship Index'],bins=bins, 
                               labels=["baixo", "medio", "alto",'muito alto'],
                               include_lowest=True)

print(data.classificacao.value_counts())
data[data.Country == 'Brazil']

muito alto    13
medio         13
baixo         13
alto          12
Name: classificacao, dtype: int64

    No Country  ... Female Labor Force Participation Rate classificacao
31   9  Brazil  ...                                  55.9         baixo

[1 rows x 10 columns]

8) Agrupe os dados por 'Level of development' e veja qual a diferença média dos desenvolvidos e não desenvolvidos em relação ao índice de empreendedorismo feminino e ao índice de empreendedorismo. Quais as conclusões que podemos chegar?

In [ ]:
data.groupby('Level of development')['Women Entrepreneurship Index'].mean()

Level of development
Developed     59.359259
Developing    34.870833
Name: Women Entrepreneurship Index, dtype: float64

In [ ]:
data.groupby('Level of development')['Entrepreneurship Index'].mean()

Level of development
Developed     59.485185
Developing    33.466667
Name: Entrepreneurship Index, dtype: float64

9) Identifique os países em que o índice de empreendedorismo feminino é maior que o índice de empreendedorismo. Quantos são?

In [ ]:
qtde = len(data[data['Women Entrepreneurship Index'] > data['Entrepreneurship Index']])
print('Temos '+str(qtde)+' países com indice de empreeendedorismo feminino maior que o de empreendedorismo')

Temos 29 países com indice de empreeendedorismo feminino maior que o de empreendedorismo

10) Ainda sobre os países que apresentam índice de empreendedorismo feminino maior que o índice de empreendedorismo, calcule o nível de desenvolvimento e a classificação mais frequente

In [ ]:
data_ = data[data['Women Entrepreneurship Index'] > data['Entrepreneurship Index']]
print('Nivel de desenvolvimento:')
print(data_['Level of development'].value_counts())
print()
print('Classificação:') 
print(data_['classificacao'].value_counts())

Nivel de desenvolvimento:
Developing    15
Developed     14
Name: Level of development, dtype: int64

Classificação:
alto          9
medio         9
baixo         7
muito alto    4
Name: classificacao, dtype: int64